__object__:
  path: depth_anything_3.model.da3_4d
  name: DepthAnything3Net
  args: as_params

net:
  __object__:
    path: depth_anything_3.model.dinov2.dinov2
    name: DinoV2
    args: as_params

  name: vitl
  out_layers: [11, 15, 19, 23]
  alt_start: 8
  qknorm_start: 8
  rope_start: 8
  cat_token: True

head:
  __object__:
    path: depth_anything_3.model.dualdpt
    name: DualDPT
    args: as_params

  dim_in: &head_dim_in 2048
  output_dim: 2
  features: &head_features 256
  out_channels: &head_out_channels [256, 512, 1024, 1024]


cam_enc:
  __object__:
    path: depth_anything_3.model.cam_enc
    name: CameraEnc
    args: as_params

  dim_out: 1024

cam_dec:
  __object__:
    path: depth_anything_3.model.cam_dec
    name: CameraDec
    args: as_params

  dim_in: 2048

# flow_head:
#   __object__:
#     path: depth_anything_3.model.flowdpt
#     name: FlowDPT
#     args: as_params

#   dim_in: 4096
#   output_dim: 2
#   features: *head_features
#   out_channels: *head_out_channels
#   activation: linear
#   use_image_context: false

raft_head:
  __object__:
    path: depth_anything_3.model.sea_raft
    name: RAFT
    args: as_params

  args:
    radius: 4
    dim: 512
    num_blocks: 2
    iters: 4
    use_var: true
    var_min: 0
    var_max: 10
    # pretrain: "resnet34"
    # initial_dim: 64
    # block_dims: [64, 128, 256]

scene_head:
  __object__:
    path: depth_anything_3.model.scene_dec_dual
    name: DualSceneDecoder
    args: as_params

  dim_in: *head_dim_in
  hid_dim: [128,256,512,1024]
  token_resize: [8,4,2,1]
  base_tokens: 200
  iters_per_frame: 1
  out_layers: [0,1,2,3]
  gs_per_token: 8
  gs_params: ['pos','scale','rot']  # 'pos','scale','rot','opac','col'